// Generated by CoffeeScript 1.12.7


class P5Transformer {
    private stack: number[][] = []
    constructor(
        public x: number = 0,
        public y: number = 0,
        public a: number = 0,
        public s: number = 1)
    {
    }

    push() {
        push();
        return this.stack.push([this.x, this.y, this.a, this.s]);
    }

    pop() {
        pop();
        let ref = this.stack.pop()
        this.x = ref![0]
        this.y = ref![1]
        this.a = ref![2]
        this.s = ref![3]
    }

    rotate(da: number) {
        rotate(da);
        return this.a += da;
    };

    scale(ds: number) {
        scale(ds);
        return this.s *= ds;
    };

    translate(dx: number, dy: number) {
        translate(dx, dy);
        this.x += this.s * dx * cos(this.a) - this.s * dy * sin(this.a);
        return this.y += this.s * dy * cos(this.a) + this.s * dx * sin(this.a);
    }

    reset() {
        this.x = 0
        this.y = 0
        this.a = 0
        this.s = 1
        this.stack = []
    }
}